[package]
name = "zik-web"
version = "0.23.3"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["fs", "cors"] }
tower = "0.5"
aws-config = "1.1"
aws-sdk-s3 = "1.15"
aws-sdk-cloudwatchlogs = "1.15"
aws-sdk-lambda = "1.15"
aws-sdk-sesv2 = "1.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
urlencoding = "2.1"
uuid = { version = "1.0", features = ["v4"] }
strudel-of-lilypond = "0.4.0"
band-songbook = "0.0.19"
circles-sketch = "0.4.0"
tempfile = "3"
chrono = "0.4"
